inoremap jj <Esc>
set nu!  " show line number
set rnu! " show relative line number
set autoindent
set smartindent
set smartcase
set smarttab
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4


if has('win32') || has('win64')
    set encoding=utf-8
    let &termencoding=&encoding
    set fileencodings=utf-8,gb18030,cp936,usc-bom,latin1
endif
